# docker compose used for testing build
version: "3.9"
services:
  api:
    build: .
    ports:
      - "8090:8080"
    environment:
      PG_HOST: "postgres"
  postgres:
    image: bitnami/postgresql:14.2.0-debian-10-r50
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: "postgres"